"""Draw og.png, the 1200x630 card every share preview and search card uses.

Run by hand (`python tools/make-og.py`), not by gen-weapon-smith.py: the site
generator has no dependencies beyond the standard library and is run on every
data change, while this needs Pillow and a font and only needs running when the
mark or the wording changes. The result is committed.

It is drawn rather than screenshotted because a screenshot of a catalogue is
576 grey thumbnails at postage-stamp size, which says nothing at the size a
share card is actually shown. The card says the name, the game, and what the
site is for, in the same three colours as the site.
"""
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
W, H = 1200, 630

BG = (6, 14, 19)            # --bg
GLOW = (14, 42, 51)         # the top-centre wash the site's body carries
TEXT = (250, 250, 250)      # --text
DIM = (149, 168, 180)       # --text-dim
FAINT = (94, 115, 129)      # --text-faint
ACCENT = (15, 247, 150)     # --accent
ACCENT_DIM = (10, 143, 87)  # --accent-dim, the hammer's haft
STEEL = (149, 168, 180)     # the anvil, --text-dim
STEEL_DIM = (94, 115, 129)  # its waist, a step back into the shadow

FONTS = pathlib.Path('C:/Windows/Fonts')


def font(*names, size=48):
    """First font that exists, at `size`. Named in preference order so this
    still produces a card on a machine without Segoe."""
    for n in names:
        p = FONTS / n
        if p.exists():
            return ImageFont.truetype(str(p), size)
    sys.exit(f'none of {names} found in {FONTS}')


def glow(img):
    """The site's background is a wide radial wash above the fold. Pillow has no
    gradient, so it is built by compositing one translucent ellipse per step —
    64 steps is smooth at this size and takes no time worth measuring."""
    steps = 64
    for i in range(steps, 0, -1):
        t = i / steps
        rx, ry = int(1500 * t), int(900 * t)
        layer = Image.new('RGBA', (W, H), (0, 0, 0, 0))
        ImageDraw.Draw(layer).ellipse(
            [W // 2 - rx, -520 - ry // 2, W // 2 + rx, -520 + ry],
            fill=GLOW + (7,))
        img.alpha_composite(layer)


def mark(d, x, y, s):
    """The favicon, at `s` pixels, top-left at (x, y).

    The same 64-unit geometry as _MARK in gen-weapon-smith.py, point for point:
    anvil face with its horn, the waist under it, the splayed foot, then the
    hammer laid on the face. Kept as polygons on both sides so the SVG and this
    cannot drift — if one moves, move the other.
    """
    u = s / 64

    def p(pts):
        return [(x + px * u, y + py * u) for px, py in pts]

    d.polygon(p([(13, 34), (49, 34), (49, 40), (13, 40), (7, 37)]), fill=STEEL)
    d.polygon(p([(24, 46), (38, 46), (45, 53), (17, 53)]), fill=STEEL)
    d.rounded_rectangle(p([(15, 52.4), (49, 56)]), radius=1.4 * u, fill=STEEL)
    d.polygon(p([(19, 40), (43, 40), (38, 46), (24, 46)]), fill=STEEL_DIM)
    d.polygon(p([(33, 30), (38, 25), (22, 9), (17, 14)]), fill=ACCENT_DIM)
    d.polygon(p([(31, 33), (38, 35), (47, 26), (45, 19), (38, 21)]), fill=ACCENT)


def tracked(d, xy, text, f, fill, space):
    """Letter-spaced text. The site's eyebrow is 0.22em of tracking and that is
    most of what makes it read as an eyebrow, so it is worth the loop."""
    x, y = xy
    for ch in text:
        d.text((x, y), ch, font=f, fill=fill)
        x += d.textlength(ch, font=f) + space


def main():
    img = Image.new('RGBA', (W, H), BG + (255,))
    glow(img)
    d = ImageDraw.Draw(img)

    pad = 88
    eyebrow = font('consolab.ttf', 'cour.ttf', size=26)
    lede = font('segoeui.ttf', 'arial.ttf', size=40)
    foot = font('consola.ttf', 'cour.ttf', size=27)

    # The mark leads the eyebrow, the way the tab icon leads the tab title, and
    # the name gets the width to itself underneath.
    mark(d, pad, 84, 76)
    tracked(d, (pad + 100, 100), 'DELTA FORCE / OPERATIONS', eyebrow, FAINT, 5.5)

    # Set to the space rather than to a number: the name is as large as fits
    # between the margins, so a longer name cannot walk off the right edge the
    # way a hardcoded 132px did.
    room = W - 2 * pad
    for size in range(124, 40, -2):
        title = font('seguibl.ttf', 'segoeuib.ttf', 'arialbd.ttf', size=size)
        if d.textlength('WEAPON SMITH', font=title) <= room:
            break
    d.text((pad, 196), 'WEAPON SMITH', font=title, fill=TEXT)

    d.text((pad, 372),
           'Every weapon, round and attachment \u2014 and which',
           font=lede, fill=DIM)
    d.text((pad, 424), 'slot each one fits.', font=lede, fill=DIM)

    # The counts are the claim: a catalogue is worth reading in proportion to
    # how much of the game is in it. Typed here rather than read from the data
    # because this file is regenerated by hand and a stale number on a share
    # card is a smaller sin than a build-time dependency on the whole generator.
    tracked(d, (pad, 516), '66 WEAPONS   89 ROUNDS   438 ATTACHMENTS',
            foot, ACCENT, 2.0)

    # A hairline of accent along the bottom, the same gesture the page's
    # section rules make.
    d.rectangle([0, H - 8, W, H], fill=ACCENT)

    out = ROOT / 'og.png'
    img.convert('RGB').save(out, optimize=True)
    print(f'wrote {out.name} ({out.stat().st_size // 1024} KB)')


if __name__ == '__main__':
    main()
